name: 'CloudFormation Changeset Reporter'
description: 'Generates color-coded reports directly in GitHub Actions logs from AWS CloudFormation changesets'
author: 'Liatrio'

inputs:
  aws-region:
    description: 'AWS region to connect to'
    required: true
    default: 'us-east-2'
  stack-name:
    description: 'Name of the CloudFormation stack'
    required: true
  changeset-name:
    description: 'Name of the changeset to report on'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'file-text'
  color: 'orange'
